hdw_main_homepage:
    path:     /
    defaults: { _controller: HDWMainBundle:Main:index }

hdw_main_insert:
    path:     /insert
    defaults: { _controller: HDWMainBundle:Main:insert }

hdw_main_remove:
    path:     /remove
    defaults: { _controller: HDWMainBundle:Main:remove }

hdw_main_select:
    path:     /select
    defaults: { _controller: HDWMainBundle:Main:select }

hdw_main_selectjoin:
    path:     /selectjoin
    defaults: { _controller: HDWMainBundle:Main:selectjoin }

hdw_main_add:
    path:     /add
    defaults: { _controller: HDWMainBundle:Main:add }

hdw_main_adddevprojetmysql:
    path:     /projetmysql
    defaults: { _controller: HDWMainBundle:Main:projetmysql }

hdw_main_adddevprojetmongo:
    path:     /projetmongo
    defaults: { _controller: HDWMainBundle:Main:projetmongo }

hdw_main_selectmany:
    path:     /selectmany
    defaults: { _controller: HDWMainBundle:Main:selectmany }